# Generated by Django 5.0 on 2023-12-04 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=uuid.UUID('a96d2c50-43cc-4616-ae15-7d4063833ce3'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
